update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Run unit tests and check library"
  lane :test do
    scan(workspace: "AutoInsetter.xcworkspace", scheme: "AutoInsetter", clean: true)
    pod_lib_lint(verbose: true)
  end

  desc "Deploy a new version"
  lane :deploy do
  end

end
